# Generated by Django 4.2.6 on 2023-10-12 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0008_remove_order_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invenory_Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_type', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone', models.PositiveBigIntegerField(unique=True)),
                ('staffid', models.IntegerField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.staff_types')),
            ],
        ),
        migrations.CreateModel(
            name='POS_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.orderitems')),
            ],
        ),
        migrations.CreateModel(
            name='POS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_inf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu.order')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TimeField()),
                ('logout', models.TimeField()),
                ('date', models.DateField()),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30, unique=True)),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.invenory_cat')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item_inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.inventory_item')),
            ],
        ),
    ]
