# Generated by Django 4.2.6 on 2023-10-12 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_staff_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_info',
            name='work',
            field=models.DurationField(default=datetime.timedelta(seconds=5400)),
        ),
    ]
