# Generated by Django 4.2.6 on 2023-10-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_alter_staff_info_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staffid',
            field=models.IntegerField(unique=True),
        ),
    ]
