# Generated by Django 4.2.6 on 2023-10-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_alter_staff_staffid'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='unit',
            field=models.CharField(default='KG', max_length=15),
        ),
    ]
