# Generated by Django 4.2.4 on 2023-10-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_customer_service_id_customer_service_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
