# Generated by Django 4.2.4 on 2023-10-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date',
        ),
    ]
