# Generated by Django 4.2.4 on 2023-10-09 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_customer_date_alter_order_service_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service_type',
        ),
    ]
